### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by DanielBolef** [siggame/Viseur#1]
Have a way (preferably a really easy way, competitors are lazy) for viewers to vote on the 'excitingness/interestingness' of a game.  Send that data somewhere where the arena can get at it.

**Comment by russleyshaw** [comment]
I think this needs to be more like thumbs up rather than thumbs down. most people are prone to really high or really low (1 & 5) scores. I think having large thumbs up/thumbs down buttons would be better

**Comment by JacobFischer** [comment]
@russleyshaw is correct. YouTube actually pointed this out in a [blog post](https://youtube.googleblog.com/2009/09/five-stars-dominate-ratings.html). Basically, with 5 star ratings, 2,3,and 4 ratings were so small as to be essentially nil. Only the 1 and 5 star ratings mattered. Any experienced eBay seller knows this as well.

_If_ we put in voting, it will be up/down based.

**Comment by jonsimington** [comment]
Shouldn't be hard to get voting set up. Arena will have to set up an endpoint for game/up and game/down, then the vis will just have some buttons that link to those endpoints

**Comment by JacobFischer** [comment]
One interesting problem: Authentication

A visualizer should not require someone to sign in, it's just a glorified log viewer. However, if they are voting up/down arena run gamelogs how do we make sure some user doesn't up/downvote some gamelog a million times?

Solutions?
1. Require signing in via some authentication service. Solves this problem but complicates the visualizer a lot for one feature not really essential to its core goal.
2. Server side just accept 1 vote from each IP/Session cookie/etc. Easy to do, but also easy to spoof. I prefer this method as I doubt SIG-GAME competitors care enough to employ bot nets to spam votes for a stupid gamelog.

**Comment by DanielBolef** [comment]
I like solution 2 as well, and it should be easy to implement arena side since we're rewriting it.

**Comment by russleyshaw** [comment]
2

**Comment by brianwgoldman** [comment]
In our current setup there are really only about 6 people who could reasonably view a gamelog: 3 members of the first player team and 3 members of the second player team. And that is assuming both teams watch it and all members feel strongly enough about it. I feel like for most of our purposes this means gamelogs are going to fall in one of four categories, ranked by how "interesting" they likely are:
1. 1 or more upvotes, no downvotes
2. 1 or more upvotes and 1 or more downvotes
3. No votes
4. 1 or more downvotes, no upvotes

If you accept my premise, then I'd argue repeated-voting is a non-issue. As I already feel that voting itself is a super low priority thing, doing any extra work to make voting more accurate seems very silly.

**Comment by jonsimington** [comment]
I keep having this vision of some reddit-style page on the vis with "interesting games to watch" with up / down vote buttons, so that people can see who is performing well or at least producing cool games throughout the competition. Having some sort of list of games sorted by score (up vote to down vote ratio) of games would increase the average number of votes on any given gamelog, too. The cream would rise to the top and, hopefully if anyone uses the page, we'd have some neat games to watch throughout.

**Comment by brianwgoldman** [comment]
If you all decide to implement voting, I'd argue it should be through the webserver and not through the visualizer.

Currently the visualizer is a nice and separate component. It receives logs as its only form of cross-component communication. To handle voting it would need to know how to send information back to the source of the log. The webserver already knows about users and logs, has a database, and talks to the arena. It seems much easier to add a button to the game's page and to leave the visualizer as a single purpose entity. This would also capture the "Reddit" style of clicking on a link, viewing its content, then going back to the source and voting.

I continue to be exceedingly skeptical of the usefulness of voting on gamelogs. I seriously doubt you can extract meaningful information from voting to decide what games to view during the tournament. If you want to make the streaming games more interesting, it seems easier to make it act like a jukebox where people just submit their games to be visualized for all to see. To me there are just so many more important things to work on.

**Comment by JacobFischer** [comment]
Closing for now. If the new arena wants this feature we can reopen this issue.

Regardless, I think Goldman is correct on all accounts.

**Comment by russleyshaw** [comment]
I think if it were to be implemented, it would be stored on the arena. there will already be a database of matches, so it would be easy to add an endpoint for voting; however, I agree. I dont think we could actually do anything with the voting info
